### ISSUE TITLE
Stolen code + GitHub pages?

### ISSUE THREAD

**Issue by Mrmagicpie** [cbrown7752/discord-machines#1]
Hey,

You have my code lmao, I fully expect you to steal it and I'm not too happy about that. But either way, GitHub pages? You can't use GitHub pages for a real bot site. GitHub pages is only static HTML so trying to trick it into allowing js or whatever to make it not static is gonna be pretty hard.

Anyway, I guess have fun with whatever you're doing?
👋

**Comment by cbrown7752** [comment]
@Mrmagicpie hello thanks for bring this to us. We are removing all code from previews code from D.M. And D.M. is not a discord bot list. If you need anything else we will be happy to help you.

**Comment by Mrmagicpie** [comment]
Alright, didn't know this changed considering for most of this repos life it was called "discord-bot-list". Thank you for removing my code.

**Comment by cbrown7752** [comment]
@Mrmagicpie np the D.M. team has just not removed everything yet
